name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contrib/**'
      - 'Makefile'
      - 'kos-libpng-dev/**'
  pull_request:
    branches: [ "main" ]

jobs:
  static-build:
    name: Static build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: Install newlib
      run: sudo apt install kos-newlib kos-zlib-dev

    - name: Build
      run: make liblibpng16.a

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-build-kos-libpng
        path: ./contrib/sdk/sources/libpng/liblibpng16.a

  shared-build:
    name: Shared Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: Install newlib
      run: sudo apt install kos-newlib kos-zlib-dev

    - name: Build
      run: make libpng16.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shared-build-kos-libpng
        path: |
          ./contrib/sdk/sources/libpng/liblibpng16.dll.a
          ./contrib/sdk/sources/libpng/libpng16.dll

  pacakage-build:
    name: Package build
    runs-on: ubuntu-latest

    needs: [static-build, shared-build]

    steps:
    - uses: actions/checkout@v4
    
    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: Install newlib
      run: sudo apt install kos-newlib kos-zlib-dev

    - name: Build
      run: make kos-libpng-dev

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-build-kos-libpng
        path: kos-libpng-dev.deb
